logging:
  level: INFO
  loggers:
    net.krvtz: DEBUG
server:
  type: simple
  applicationContextPath: /app
  connector:
    type: http
    port: 8888
#database:
#  url: 'jdbc:h2:mem:drop-goat'
#  driverClass: "org.h2.Driver"